// Philosophers, eras, schools, relations — canonical dataset for the prototype.
// Year uses negatives for BCE. Each philosopher has a school list (main memberships).

const ERAS = [
  { id: 'ancient',     zh: '古希腊',   en: 'Ancient Greek',   start: -600, end:  400 },
  { id: 'medieval',    zh: '中世纪',   en: 'Medieval',        start:  400, end: 1400 },
  { id: 'renaissance', zh: '文艺复兴', en: 'Renaissance',     start: 1400, end: 1600 },
  { id: 'early_modern',zh: '近代',     en: 'Early Modern',    start: 1600, end: 1800 },
  { id: 'modern',      zh: '现代',     en: 'Modern',          start: 1800, end: 1945 },
  { id: 'contemporary',zh: '当代',     en: 'Contemporary',    start: 1945, end: 2030 },
];

// Schools / movements. Lane assignment controls vertical position on star map.
const SCHOOLS = [
  { id: 'presocratic',  zh: '前苏格拉底',       en: 'Pre-Socratic',           lane: 0.82 },
  { id: 'classical',    zh: '古典希腊',         en: 'Classical Greek',        lane: 0.48 },
  { id: 'hellenistic',  zh: '希腊化',           en: 'Hellenistic',            lane: 0.68 },
  { id: 'stoic',        zh: '斯多葛',           en: 'Stoicism',               lane: 0.30 },
  { id: 'epicurean',    zh: '伊壁鸠鲁',         en: 'Epicureanism',           lane: 0.82 },
  { id: 'skeptic',      zh: '怀疑主义',         en: 'Skepticism',             lane: 0.18 },
  { id: 'neoplatonic',  zh: '新柏拉图主义',     en: 'Neoplatonism',           lane: 0.45 },
  { id: 'scholastic',   zh: '经院哲学',         en: 'Scholasticism',          lane: 0.50 },
  { id: 'rationalism',  zh: '理性主义',         en: 'Rationalism',            lane: 0.32 },
  { id: 'empiricism',   zh: '经验主义',         en: 'Empiricism',             lane: 0.72 },
  { id: 'enlightenment',zh: '启蒙理性',         en: 'Enlightenment',          lane: 0.58 },
  { id: 'idealism',     zh: '唯心主义',         en: 'Idealism',               lane: 0.22 },
  { id: 'german_classical', zh: '德国古典哲学', en: 'German Classical',       lane: 0.28 },
  { id: 'materialism',  zh: '唯物主义',         en: 'Materialism',            lane: 0.85 },
  { id: 'pragmatism',   zh: '实用主义',         en: 'Pragmatism',             lane: 0.68 },
  { id: 'phenomenology',zh: '现象学',           en: 'Phenomenology',          lane: 0.38 },
  { id: 'existentialism',zh: '存在主义',        en: 'Existentialism',         lane: 0.48 },
  { id: 'analytic',     zh: '分析哲学',         en: 'Analytic',               lane: 0.78 },
  { id: 'linguistic',   zh: '语言哲学',         en: 'Linguistic Philosophy',  lane: 0.82 },
  { id: 'structuralism',zh: '结构主义',         en: 'Structuralism',          lane: 0.62 },
  { id: 'poststructuralism', zh: '后结构主义',  en: 'Post-Structuralism',     lane: 0.55 },
  { id: 'critical',     zh: '批判理论',         en: 'Critical Theory',        lane: 0.42 },
];

// Relation types — color assigned in the component.
// kind ∈ 'teacher' | 'develop' | 'critique' | 'influence'
// Direction rule:
// - teacher/develop/influence: source shapes target.
// - critique: target is a major critic of source.
// Keep only durable, historically legible relationships. Avoid loose analogy.
const RELATIONS = [
  // — Ancient —
  ['thales',       'anaximander', 'teacher'],
  ['pythagoras',   'plato',       'influence'],
  ['heraclitus',   'plato',       'influence'],
  ['heraclitus',   'hegel',       'influence'],
  ['parmenides',   'zeno_elea',   'teacher'],
  ['parmenides',   'empedocles',  'influence'],
  ['parmenides',   'plato',       'influence'],
  ['anaxagoras',   'socrates',    'influence'],
  ['democritus',   'epicurus',    'influence'],
  ['protagoras',   'plato',       'critique'],
  ['socrates',     'plato',       'teacher'],
  ['plato',        'aristotle',   'teacher'],
  ['plato',        'plotinus',    'influence'],
  ['plato',        'cicero',      'influence'],
  ['plato',        'boethius',    'influence'],
  ['plato',        'augustine',   'influence'],
  ['aristotle',    'avicenna',    'influence'],
  ['aristotle',    'averroes',    'influence'],
  ['aristotle',    'maimonides',  'influence'],
  ['aristotle',    'aquinas',     'influence'],
  ['aristotle',    'macintyre',   'influence'],
  ['diogenes',     'zeno_citium', 'influence'],
  ['pyrrho',       'montaigne',   'influence'],
  ['epicurus',     'lucretius',   'influence'],
  ['zeno_citium',  'seneca',      'influence'],
  ['zeno_citium',  'epictetus',   'influence'],
  ['seneca',       'epictetus',   'influence'],
  ['epictetus',    'marcus',      'influence'],
  ['plotinus',     'augustine',   'influence'],
  ['plotinus',     'hypatia',     'influence'],

  // — Medieval —
  ['augustine',    'boethius',    'influence'],
  ['augustine',    'anselm',      'influence'],
  ['augustine',    'aquinas',     'influence'],
  ['boethius',     'aquinas',     'influence'],
  ['anselm',       'aquinas',     'influence'],
  ['avicenna',     'aquinas',     'influence'],
  ['averroes',     'aquinas',     'influence'],
  ['maimonides',   'aquinas',     'influence'],
  ['aquinas',      'scotus',      'critique'],
  ['aquinas',      'ockham',      'critique'],
  ['aquinas',      'macintyre',   'influence'],
  ['scotus',       'ockham',      'influence'],

  // — Early modern —
  ['machiavelli',  'hobbes',      'influence'],
  ['montaigne',    'descartes',   'influence'],
  ['montaigne',    'pascal',      'influence'],
  ['bacon',        'hobbes',      'influence'],
  ['bacon',        'locke',       'influence'],
  ['hobbes',       'locke',       'critique'],
  ['hobbes',       'rousseau',    'critique'],
  ['descartes',    'spinoza',     'develop'],
  ['descartes',    'leibniz',     'develop'],
  ['descartes',    'locke',       'critique'],
  ['spinoza',      'hegel',       'influence'],
  ['spinoza',      'nietzsche',   'influence'],
  ['spinoza',      'deleuze',     'influence'],
  ['locke',        'berkeley',    'develop'],
  ['locke',        'hume',        'develop'],
  ['locke',        'voltaire',    'influence'],
  ['locke',        'montesquieu', 'influence'],
  ['locke',        'rousseau',    'influence'],
  ['locke',        'wollstonecraft', 'influence'],
  ['berkeley',     'hume',        'critique'],
  ['hume',         'kant',        'influence'],
  ['leibniz',      'kant',        'influence'],
  ['voltaire',     'diderot',     'develop'],
  ['diderot',      'rousseau',    'influence'],
  ['rousseau',     'kant',        'influence'],
  ['rousseau',     'hegel',       'influence'],
  ['rousseau',     'wollstonecraft', 'critique'],

  // — German Classical —
  ['kant',         'fichte',      'develop'],
  ['kant',         'schelling',   'influence'],
  ['kant',         'hegel',       'critique'],
  ['kant',         'schopenhauer','influence'],
  ['kant',         'rawls',       'influence'],
  ['kant',         'habermas',    'influence'],
  ['kant',         'weil',        'influence'],
  ['fichte',       'schelling',   'develop'],
  ['fichte',       'hegel',       'influence'],
  ['schelling',    'hegel',       'develop'],
  ['hegel',        'feuerbach',   'critique'],
  ['hegel',        'schopenhauer','critique'],
  ['hegel',        'marx',        'critique'],
  ['hegel',        'kierkegaard', 'critique'],
  ['hegel',        'adorno',      'influence'],
  ['hegel',        'zizek',       'influence'],
  ['feuerbach',    'marx',        'influence'],

  // — Modern —
  ['bentham',      'mill',        'develop'],
  ['mill',         'james',       'influence'],
  ['bentham',      'singer',      'influence'],
  ['mill',         'singer',      'develop'],
  ['schopenhauer', 'nietzsche',   'influence'],
  ['kierkegaard',  'jaspers',     'influence'],
  ['kierkegaard',  'buber',       'influence'],
  ['kierkegaard',  'heidegger',   'influence'],
  ['kierkegaard',  'sartre',      'influence'],
  ['nietzsche',    'heidegger',   'influence'],
  ['nietzsche',    'foucault',    'influence'],
  ['nietzsche',    'derrida',     'influence'],
  ['nietzsche',    'deleuze',     'influence'],
  ['bergson',      'deleuze',     'influence'],
  ['peirce',       'james',       'teacher'],
  ['peirce',       'dewey',       'influence'],
  ['james',        'dewey',       'influence'],
  ['moore',        'russell',     'develop'],
  ['moore',        'wittgenstein','influence'],
  ['whitehead',    'russell',     'teacher'],
  ['frege',        'russell',     'influence'],
  ['frege',        'wittgenstein','influence'],
  ['frege',        'carnap',      'influence'],
  ['russell',      'wittgenstein','teacher'],
  ['russell',      'quine',       'influence'],
  ['russell',      'carnap',      'influence'],
  ['husserl',      'heidegger',   'teacher'],
  ['husserl',      'sartre',      'influence'],
  ['husserl',      'merleau',     'influence'],
  ['husserl',      'levinas',     'influence'],
  ['husserl',      'ricoeur',     'influence'],
  ['heidegger',    'sartre',      'influence'],
  ['heidegger',    'arendt',      'teacher'],
  ['heidegger',    'gadamer',     'teacher'],
  ['heidegger',    'levinas',     'influence'],
  ['heidegger',    'derrida',     'influence'],
  ['heidegger',    'ricoeur',     'influence'],
  ['heidegger',    'rorty',       'influence'],
  ['sartre',       'beauvoir',    'develop'],
  ['sartre',       'camus',       'critique'],
  ['beauvoir',     'butler',      'influence'],
  ['marx',         'gramsci',     'develop'],
  ['marx',         'horkheimer',  'develop'],
  ['marx',         'adorno',      'develop'],
  ['marx',         'benjamin',    'influence'],
  ['marx',         'marcuse',     'develop'],
  ['marx',         'althusser',   'develop'],
  ['horkheimer',   'adorno',      'develop'],
  ['horkheimer',   'marcuse',     'teacher'],
  ['adorno',       'benjamin',    'influence'],
  ['adorno',       'habermas',    'teacher'],

  // — Structuralism / Post-Structuralism —
  ['saussure',     'levi_strauss','influence'],
  ['saussure',     'barthes',     'influence'],
  ['saussure',     'lacan',       'influence'],
  ['saussure',     'chomsky',     'critique'],
  ['levi_strauss', 'foucault',    'influence'],
  ['levi_strauss', 'barthes',     'influence'],
  ['lacan',        'althusser',   'influence'],
  ['lacan',        'zizek',       'influence'],
  ['lacan',        'butler',      'influence'],
  ['foucault',     'butler',      'influence'],
  ['derrida',      'butler',      'influence'],

  // — Contemporary analytic / political philosophy —
  ['wittgenstein', 'austin',      'influence'],
  ['wittgenstein', 'schlick',     'influence'],
  ['wittgenstein', 'carnap',      'influence'],
  ['wittgenstein', 'kripke',      'influence'],
  ['wittgenstein', 'rorty',       'influence'],
  ['wittgenstein', 'searle',      'influence'],
  ['schlick',      'carnap',      'develop'],
  ['tarski',       'quine',       'influence'],
  ['tarski',       'davidson',    'influence'],
  ['quine',        'davidson',    'influence'],
  ['quine',        'putnam',      'influence'],
  ['quine',        'dennett',     'influence'],
  ['austin',       'searle',      'teacher'],
  ['sellars',      'rorty',       'teacher'],
  ['sellars',      'davidson',    'influence'],
  ['dewey',        'rorty',       'influence'],
  ['popper',       'kuhn',        'critique'],
  ['kripke',       'lewis_d',     'critique'],
  ['hume',         'parfit',      'influence'],
  ['dennett',      'chalmers',    'critique'],
  ['rawls',        'nozick',      'critique'],
];

// Philosophers. year = birth year (used for x position).
// Using real lived years; portrait = slug for local placeholder.
const PHILOSOPHERS = [
  // Pre-Socratics
  { id:'thales',      zh:'泰勒斯',       en:'Thales',        year:-624, died:-546, schools:['presocratic'], era:'ancient', blurb:'西方哲学之父，宣称"万物源于水"。' },
  { id:'anaximander', zh:'阿那克西曼德', en:'Anaximander',   year:-610, died:-546, schools:['presocratic'], era:'ancient', blurb:'提出"无定"（Apeiron）作为万物本原。' },
  { id:'pythagoras',  zh:'毕达哥拉斯',   en:'Pythagoras',    year:-570, died:-495, schools:['presocratic'], era:'ancient', blurb:'数即宇宙本原；灵魂不灭与转世。' },
  { id:'heraclitus',  zh:'赫拉克利特',   en:'Heraclitus',    year:-535, died:-475, schools:['presocratic'], era:'ancient', blurb:'万物流变；对立统一的辩证端倪。' },
  { id:'parmenides',  zh:'巴门尼德',     en:'Parmenides',    year:-515, died:-450, schools:['presocratic'], era:'ancient', blurb:'存在唯一、不变；反对流变说。' },
  { id:'zeno_elea',   zh:'芝诺（爱利亚）', en:'Zeno of Elea', year:-490, died:-430, schools:['presocratic'], era:'ancient', blurb:'以悖论捍卫巴门尼德的一元论。' },
  { id:'democritus',  zh:'德谟克利特',   en:'Democritus',    year:-460, died:-370, schools:['presocratic'], era:'ancient', blurb:'原子论奠基者。', blurb_en:'Founder of atomism.' },
  { id:'protagoras',  zh:'普罗泰戈拉',   en:'Protagoras',    year:-490, died:-420, schools:['classical'], era:'ancient', blurb:'智者派代表；相对主义先驱。', blurb_en:'Leading Sophist; early relativist.' },

  // Classical
  { id:'socrates',    zh:'苏格拉底',     en:'Socrates',      year:-470, died:-399, schools:['classical'], era:'ancient', blurb:'以诘问法追问德性与知识。' },
  { id:'plato',       zh:'柏拉图',       en:'Plato',         year:-428, died:-348, schools:['classical'], era:'ancient', blurb:'理念论；《理想国》；学园。' },
  { id:'aristotle',   zh:'亚里士多德',   en:'Aristotle',     year:-384, died:-322, schools:['classical'], era:'ancient', blurb:'形而上学、逻辑学、伦理学奠基人。' },

  // Hellenistic
  { id:'diogenes',    zh:'第欧根尼',     en:'Diogenes',      year:-412, died:-323, schools:['hellenistic'], era:'ancient', blurb:'犬儒哲学的化身。' },
  { id:'pyrrho',      zh:'皮浪',         en:'Pyrrho',        year:-360, died:-270, schools:['skeptic'],     era:'ancient', blurb:'古希腊怀疑主义鼻祖。' },
  { id:'epicurus',    zh:'伊壁鸠鲁',     en:'Epicurus',      year:-341, died:-270, schools:['epicurean'],   era:'ancient', blurb:'快乐即善；原子论自然观。' },
  { id:'zeno_citium', zh:'芝诺（季蒂昂）', en:'Zeno of Citium',year:-334,died:-262, schools:['stoic'],      era:'ancient', blurb:'斯多葛派创始人。' },

  // Roman / late ancient
  { id:'epictetus',   zh:'爱比克泰德',   en:'Epictetus',     year:  50, died: 135,  schools:['stoic'],      era:'ancient', blurb:'《手册》作者；晚期斯多葛。' },
  { id:'marcus',      zh:'马可·奥勒留', en:'Marcus Aurelius',year: 121, died: 180,  schools:['stoic'],      era:'ancient', blurb:'帝王哲学家；《沉思录》。' },
  { id:'plotinus',    zh:'普罗提诺',     en:'Plotinus',      year: 204, died: 270,  schools:['neoplatonic'],era:'ancient', blurb:'新柏拉图主义奠基人。' },

  // Medieval
  { id:'augustine',   zh:'奥古斯丁',     en:'Augustine',     year: 354, died: 430,  schools:['neoplatonic','scholastic'], era:'medieval', blurb:'《忏悔录》；基督教哲学奠基。' },
  { id:'avicenna',    zh:'阿维森纳',     en:'Avicenna',      year: 980, died:1037,  schools:['scholastic'], era:'medieval', blurb:'伊斯兰亚里士多德主义巨匠。' },
  { id:'anselm',      zh:'安瑟伦',       en:'Anselm',        year:1033, died:1109,  schools:['scholastic'], era:'medieval', blurb:'本体论证明。' },
  { id:'averroes',    zh:'阿威罗伊',     en:'Averroes',      year:1126, died:1198,  schools:['scholastic'], era:'medieval', blurb:'亚里士多德的伟大注疏者。' },
  { id:'aquinas',     zh:'阿奎那',       en:'Aquinas',       year:1225, died:1274,  schools:['scholastic'], era:'medieval', blurb:'《神学大全》；信仰与理性的综合。' },
  { id:'ockham',      zh:'奥卡姆',       en:'Ockham',        year:1287, died:1347,  schools:['scholastic'], era:'medieval', blurb:'唯名论；奥卡姆剃刀。' },

  // Renaissance
  { id:'bacon',       zh:'弗朗西斯·培根',en:'Francis Bacon', year:1561, died:1626,  schools:['empiricism'], era:'renaissance', blurb:'归纳法；新工具论。' },

  // Early modern
  { id:'hobbes',      zh:'霍布斯',       en:'Hobbes',        year:1588, died:1679,  schools:['empiricism','materialism'], era:'early_modern', blurb:'社会契约；利维坦。' },
  { id:'descartes',   zh:'笛卡尔',       en:'Descartes',     year:1596, died:1650,  schools:['rationalism'], era:'early_modern', blurb:'近代哲学之父；我思故我在。' },
  { id:'spinoza',     zh:'斯宾诺莎',     en:'Spinoza',       year:1632, died:1677,  schools:['rationalism'], era:'early_modern', blurb:'泛神论；几何学方式的伦理学。' },
  { id:'locke',       zh:'洛克',         en:'Locke',         year:1632, died:1704,  schools:['empiricism'], era:'early_modern', blurb:'经验主义；白板说；政府论。' },
  { id:'leibniz',     zh:'莱布尼茨',     en:'Leibniz',       year:1646, died:1716,  schools:['rationalism'], era:'early_modern', blurb:'单子论；充足理由律。' },
  { id:'berkeley',    zh:'贝克莱',       en:'Berkeley',      year:1685, died:1753,  schools:['empiricism','idealism'], era:'early_modern', blurb:'存在即被感知。' },
  { id:'hume',        zh:'休谟',         en:'Hume',          year:1711, died:1776,  schools:['empiricism'], era:'early_modern', blurb:'怀疑论；因果问题。', blurb_en:'Skepticism; the problem of causation.' },
  { id:'pascal',      zh:'帕斯卡',       en:'Pascal',        year:1623, died:1662,  schools:['rationalism'], era:'early_modern', blurb:'思想芦苇；赌注论证。', blurb_en:'Thinking reed; the wager.' },
  { id:'voltaire',    zh:'伏尔泰',       en:'Voltaire',      year:1694, died:1778,  schools:['enlightenment'], era:'early_modern', blurb:'启蒙运动旗手；自然神论。', blurb_en:'Champion of the Enlightenment.' },
  { id:'bentham',     zh:'边沁',         en:'Bentham',       year:1748, died:1832,  schools:['empiricism'], era:'modern', blurb:'功利主义奠基人。', blurb_en:'Founder of utilitarianism.' },
  { id:'moore',       zh:'摩尔',         en:'G. E. Moore',   year:1873, died:1958,  schools:['analytic'], era:'modern', blurb:'常识实在论；自然主义谬误。', blurb_en:'Common-sense realism.' },
  { id:'whitehead',   zh:'怀特海',       en:'Whitehead',     year:1861, died:1947,  schools:['analytic'], era:'modern', blurb:'过程哲学；《数学原理》合著。', blurb_en:'Process philosophy.' },
  { id:'popper',      zh:'波普尔',       en:'Popper',        year:1902, died:1994,  schools:['analytic'], era:'contemporary', blurb:'科学哲学；可证伪性。', blurb_en:'Philosophy of science; falsifiability.' },
  { id:'kuhn',        zh:'库恩',         en:'Kuhn',          year:1922, died:1996,  schools:['analytic'], era:'contemporary', blurb:'范式转换；科学革命。', blurb_en:'Paradigm shifts.' },
  { id:'gadamer',     zh:'伽达默尔',     en:'Gadamer',       year:1900, died:2002,  schools:['phenomenology'], era:'contemporary', blurb:'哲学诠释学；真理与方法。', blurb_en:'Philosophical hermeneutics.' },
  { id:'levinas',     zh:'列维纳斯',     en:'Levinas',       year:1906, died:1995,  schools:['phenomenology'], era:'contemporary', blurb:'他者哲学；伦理为第一哲学。', blurb_en:'Ethics as first philosophy.' },
  { id:'chomsky',     zh:'乔姆斯基',     en:'Chomsky',       year:1928, died:null,  schools:['analytic','linguistic'], era:'contemporary', blurb:'生成语法；普遍语法假说。', blurb_en:'Generative grammar.' },
  { id:'nozick',      zh:'诺齐克',       en:'Nozick',        year:1938, died:2002,  schools:['analytic'], era:'contemporary', blurb:'最小国家；正义的权利理论。', blurb_en:'Minimal state; entitlement theory.' },
  { id:'macintyre',   zh:'麦金太尔',     en:'MacIntyre',     year:1929, died:null,  schools:['analytic'], era:'contemporary', blurb:'德性伦理学复兴；追寻美德。', blurb_en:'Revival of virtue ethics.' },
  { id:'zizek',       zh:'齐泽克',       en:'Žižek',         year:1949, died:null,  schools:['poststructuralism','critical'], era:'contemporary', blurb:'拉康派马克思主义；意识形态分析。', blurb_en:'Lacanian Marxism; ideology critique.' },
  { id:'rousseau',    zh:'卢梭',         en:'Rousseau',      year:1712, died:1778,  schools:['enlightenment'], era:'early_modern', blurb:'社会契约论；自然状态。' },
  { id:'kant',        zh:'康德',         en:'Kant',          year:1724, died:1804,  schools:['enlightenment','german_classical','idealism'], era:'early_modern', blurb:'批判哲学；先验综合判断。' },
  { id:'fichte',      zh:'费希特',       en:'Fichte',        year:1762, died:1814,  schools:['german_classical','idealism'], era:'early_modern', blurb:'知识学；自我设定非我。' },

  // Modern
  { id:'hegel',       zh:'黑格尔',       en:'Hegel',         year:1770, died:1831,  schools:['german_classical','idealism'], era:'modern', blurb:'绝对精神；辩证法。' },
  { id:'schelling',   zh:'谢林',         en:'Schelling',     year:1775, died:1854,  schools:['german_classical','idealism'], era:'modern', blurb:'自然哲学与同一哲学。' },
  { id:'schopenhauer',zh:'叔本华',       en:'Schopenhauer',  year:1788, died:1860,  schools:['idealism'],     era:'modern', blurb:'作为意志与表象的世界。' },
  { id:'feuerbach',   zh:'费尔巴哈',     en:'Feuerbach',     year:1804, died:1872,  schools:['materialism'],  era:'modern', blurb:'人本学唯物主义。' },
  { id:'mill',        zh:'密尔',         en:'J. S. Mill',    year:1806, died:1873,  schools:['empiricism'],   era:'modern', blurb:'功利主义；论自由。' },
  { id:'kierkegaard', zh:'克尔凯郭尔',   en:'Kierkegaard',   year:1813, died:1855,  schools:['existentialism'],era:'modern', blurb:'存在主义之父。' },
  { id:'marx',        zh:'马克思',       en:'Marx',          year:1818, died:1883,  schools:['materialism','critical'], era:'modern', blurb:'历史唯物主义；资本论。' },
  { id:'peirce',      zh:'皮尔士',       en:'Peirce',        year:1839, died:1914,  schools:['pragmatism'],   era:'modern', blurb:'实用主义创始人；符号学。' },
  { id:'james',       zh:'威廉·詹姆斯', en:'William James', year:1842, died:1910,  schools:['pragmatism'],   era:'modern', blurb:'实用主义心理学。' },
  { id:'nietzsche',   zh:'尼采',         en:'Nietzsche',     year:1844, died:1900,  schools:['existentialism'],era:'modern', blurb:'权力意志；超人；上帝已死。' },
  { id:'frege',       zh:'弗雷格',       en:'Frege',         year:1848, died:1925,  schools:['analytic'],     era:'modern', blurb:'现代逻辑奠基人。' },
  { id:'husserl',     zh:'胡塞尔',       en:'Husserl',       year:1859, died:1938,  schools:['phenomenology'],era:'modern', blurb:'现象学运动奠基人。' },
  { id:'dewey',       zh:'杜威',         en:'Dewey',         year:1859, died:1952,  schools:['pragmatism'],   era:'modern', blurb:'工具主义；民主与教育。' },
  { id:'saussure',    zh:'索绪尔',       en:'Saussure',      year:1857, died:1913,  schools:['structuralism','linguistic'], era:'modern', blurb:'结构语言学之父。' },
  { id:'bergson',     zh:'柏格森',       en:'Bergson',       year:1859, died:1941,  schools:['phenomenology'],era:'modern', blurb:'生命冲动；绵延。' },
  { id:'russell',     zh:'罗素',         en:'Russell',       year:1872, died:1970,  schools:['analytic'],     era:'modern', blurb:'数学哲学；描述理论。' },
  { id:'wittgenstein',zh:'维特根斯坦',   en:'Wittgenstein',  year:1889, died:1951,  schools:['analytic','linguistic'], era:'modern', blurb:'前期《逻辑哲学论》；后期语言游戏。' },
  { id:'heidegger',   zh:'海德格尔',     en:'Heidegger',     year:1889, died:1976,  schools:['phenomenology','existentialism'], era:'modern', blurb:'存在与时间；此在分析。' },

  // Contemporary
  { id:'arendt',      zh:'阿伦特',       en:'Arendt',        year:1906, died:1975,  schools:['existentialism','critical'], era:'contemporary', blurb:'人的境况；平庸之恶。' },
  { id:'sartre',      zh:'萨特',         en:'Sartre',        year:1905, died:1980,  schools:['existentialism','phenomenology'], era:'contemporary', blurb:'存在主义；自由与自为。' },
  { id:'beauvoir',    zh:'波伏瓦',       en:'Beauvoir',      year:1908, died:1986,  schools:['existentialism'],  era:'contemporary', blurb:'第二性；女性主义存在主义。' },
  { id:'merleau',     zh:'梅洛-庞蒂',    en:'Merleau-Ponty', year:1908, died:1961,  schools:['phenomenology'],   era:'contemporary', blurb:'知觉现象学；身体主体。' },
  { id:'camus',       zh:'加缪',         en:'Camus',         year:1913, died:1960,  schools:['existentialism'],  era:'contemporary', blurb:'荒诞哲学；反抗。' },
  { id:'quine',       zh:'蒯因',         en:'Quine',         year:1908, died:2000,  schools:['analytic'],        era:'contemporary', blurb:'整体论；本体论承诺。' },
  { id:'austin',      zh:'奥斯汀',       en:'Austin',        year:1911, died:1960,  schools:['analytic','linguistic'], era:'contemporary', blurb:'言语行为理论。' },
  { id:'adorno',      zh:'阿多诺',       en:'Adorno',        year:1903, died:1969,  schools:['critical'],        era:'contemporary', blurb:'启蒙辩证法；否定辩证法。' },
  { id:'levi_strauss',zh:'列维-施特劳斯',en:'Lévi-Strauss',  year:1908, died:2009,  schools:['structuralism'],   era:'contemporary', blurb:'结构人类学。' },
  { id:'rawls',       zh:'罗尔斯',       en:'Rawls',         year:1921, died:2002,  schools:['analytic'],        era:'contemporary', blurb:'正义论；无知之幕。' },
  { id:'foucault',    zh:'福柯',         en:'Foucault',      year:1926, died:1984,  schools:['poststructuralism','critical'], era:'contemporary', blurb:'知识/权力；话语分析。' },
  { id:'habermas',    zh:'哈贝马斯',     en:'Habermas',      year:1929, died:2024,  schools:['critical'],        era:'contemporary', blurb:'交往行动理论。' },
  { id:'derrida',     zh:'德里达',       en:'Derrida',       year:1930, died:2004,  schools:['poststructuralism'],era:'contemporary', blurb:'解构主义；延异。' },
  { id:'rorty',       zh:'罗蒂',         en:'Rorty',         year:1931, died:2007,  schools:['pragmatism','analytic'], era:'contemporary', blurb:'新实用主义；反本质主义。' },
  { id:'deleuze',     zh:'德勒兹',       en:'Deleuze',       year:1925, died:1995,  schools:['poststructuralism'],era:'contemporary', blurb:'差异与重复；根茎。' },
  { id:'kripke',      zh:'克里普克',     en:'Kripke',        year:1940, died:2022,  schools:['analytic'],        era:'contemporary', blurb:'可能世界；命名与必然性。' },
  { id:'davidson',    zh:'戴维森',       en:'Davidson',      year:1917, died:2003,  schools:['analytic'],        era:'contemporary', blurb:'真值条件语义；诠释。' },
  { id:'butler',      zh:'巴特勒',       en:'Butler',        year:1956, died:null,  schools:['poststructuralism','critical'], era:'contemporary', blurb:'性别操演。' },

  // — Additions —
  // Late ancient / medieval bridge
  { id:'boethius',    zh:'波爱修',       en:'Boethius',      year: 477, died: 524,  schools:['neoplatonic','scholastic'], era:'medieval', blurb:'古典与中世纪的桥梁；《哲学的慰藉》。', blurb_en:'Bridge between antiquity and the medieval; Consolation of Philosophy.' },

  // Renaissance
  { id:'machiavelli', zh:'马基雅维利',   en:'Machiavelli',   year:1469, died:1527,  schools:['enlightenment'], era:'renaissance', blurb:'政治现实主义；《君主论》。', blurb_en:'Political realism; The Prince.' },
  { id:'montaigne',   zh:'蒙田',         en:'Montaigne',     year:1533, died:1592,  schools:['skeptic'], era:'renaissance', blurb:'现代随笔之父；温和怀疑主义。', blurb_en:'Father of the modern essay.' },

  // Enlightenment additions
  { id:'montesquieu', zh:'孟德斯鸠',     en:'Montesquieu',   year:1689, died:1755,  schools:['enlightenment'], era:'early_modern', blurb:'三权分立；《论法的精神》。', blurb_en:'Separation of powers.' },
  { id:'diderot',     zh:'狄德罗',       en:'Diderot',       year:1713, died:1784,  schools:['enlightenment','materialism'], era:'early_modern', blurb:'百科全书派主编；唯物启蒙。', blurb_en:'Editor of the Encyclopédie.' },

  // Critical theory / Marxism
  { id:'gramsci',     zh:'葛兰西',       en:'Gramsci',       year:1891, died:1937,  schools:['critical','materialism'], era:'modern', blurb:'文化霸权；实践哲学。', blurb_en:'Cultural hegemony.' },
  { id:'horkheimer',  zh:'霍克海默',     en:'Horkheimer',    year:1895, died:1973,  schools:['critical'], era:'modern', blurb:'法兰克福学派创始；启蒙辩证法。', blurb_en:'Founder of the Frankfurt School.' },
  { id:'benjamin',    zh:'本雅明',       en:'W. Benjamin',   year:1892, died:1940,  schools:['critical'], era:'modern', blurb:'机械复制时代；历史天使。', blurb_en:'The Angel of History.' },
  { id:'marcuse',     zh:'马尔库塞',     en:'Marcuse',       year:1898, died:1979,  schools:['critical'], era:'contemporary', blurb:'单向度的人；爱欲与文明。', blurb_en:'One-Dimensional Man.' },

  // Phenomenology / existential (religious & hermeneutic)
  { id:'jaspers',     zh:'雅斯贝尔斯',   en:'Jaspers',       year:1883, died:1969,  schools:['existentialism','phenomenology'], era:'modern', blurb:'实存哲学；轴心时代。', blurb_en:'Existenz philosophy; the Axial Age.' },
  { id:'buber',       zh:'布伯',         en:'Buber',         year:1878, died:1965,  schools:['existentialism','phenomenology'], era:'modern', blurb:'我与你；对话哲学。', blurb_en:'I and Thou; dialogical philosophy.' },
  { id:'ricoeur',     zh:'利科',         en:'Ricoeur',       year:1913, died:2005,  schools:['phenomenology'], era:'contemporary', blurb:'叙事与诠释；怀疑的诠释学。', blurb_en:'Narrative and hermeneutics.' },

  // Post-structuralism / psychoanalysis
  { id:'lacan',       zh:'拉康',         en:'Lacan',         year:1901, died:1981,  schools:['poststructuralism','structuralism'], era:'contemporary', blurb:'返回弗洛伊德；镜像阶段。', blurb_en:'Return to Freud; the mirror stage.' },
  { id:'althusser',   zh:'阿尔都塞',     en:'Althusser',     year:1918, died:1990,  schools:['poststructuralism','critical','materialism'], era:'contemporary', blurb:'结构主义马克思主义；意识形态国家机器。', blurb_en:'Structuralist Marxism; ISAs.' },
  { id:'barthes',     zh:'罗兰·巴特',   en:'Barthes',       year:1915, died:1980,  schools:['structuralism','poststructuralism'], era:'contemporary', blurb:'符号学；作者之死。', blurb_en:'Semiology; the death of the author.' },

  // Logical positivism / analytic additions
  { id:'carnap',      zh:'卡尔纳普',     en:'Carnap',        year:1891, died:1970,  schools:['analytic'], era:'modern', blurb:'维也纳学派；逻辑经验主义。', blurb_en:'Vienna Circle; logical empiricism.' },
  { id:'schlick',     zh:'石里克',       en:'Schlick',       year:1882, died:1936,  schools:['analytic'], era:'modern', blurb:'维也纳学派领袖；可证实原则。', blurb_en:'Leader of the Vienna Circle.' },
  { id:'tarski',      zh:'塔尔斯基',     en:'Tarski',        year:1901, died:1983,  schools:['analytic'], era:'modern', blurb:'真理的语义定义。', blurb_en:'Semantic theory of truth.' },

  // Analytic contemporary
  { id:'putnam',      zh:'普特南',       en:'Putnam',        year:1926, died:2016,  schools:['analytic'], era:'contemporary', blurb:'功能主义；内在实在论。', blurb_en:'Functionalism; internal realism.' },
  { id:'searle',      zh:'塞尔',         en:'Searle',        year:1932, died:null,  schools:['analytic','linguistic'], era:'contemporary', blurb:'言语行为；中文屋论证。', blurb_en:'Speech acts; Chinese Room.' },
  { id:'dennett',     zh:'丹尼特',       en:'Dennett',       year:1942, died:2024,  schools:['analytic'], era:'contemporary', blurb:'意识的多重草稿模型。', blurb_en:'Multiple drafts model of consciousness.' },
  { id:'chalmers',    zh:'查尔默斯',     en:'Chalmers',      year:1966, died:null,  schools:['analytic'], era:'contemporary', blurb:'意识的"困难问题"。', blurb_en:'The hard problem of consciousness.' },
  { id:'lewis_d',     zh:'大卫·刘易斯', en:'David Lewis',   year:1941, died:2001,  schools:['analytic'], era:'contemporary', blurb:'模态实在论；可能世界。', blurb_en:'Modal realism; possible worlds.' },
  { id:'parfit',      zh:'帕菲特',       en:'Parfit',        year:1942, died:2017,  schools:['analytic'], era:'contemporary', blurb:'人格同一性；理性与人。', blurb_en:'Personal identity.' },
  { id:'singer',      zh:'辛格',         en:'Singer',        year:1946, died:null,  schools:['analytic'], era:'contemporary', blurb:'应用伦理学；动物解放。', blurb_en:'Applied ethics; animal liberation.' },
  { id:'sellars',     zh:'塞拉斯',       en:'Sellars',       year:1912, died:1989,  schools:['analytic'], era:'contemporary', blurb:'给予的神话；科学与显象。', blurb_en:'The myth of the given.' },

  // Contemporary French (neo-structural)

  // Additional pre-Socratic & ancient
  { id:'anaxagoras',  zh:'阿那克萨戈拉', en:'Anaxagoras',    year:-500, died:-428,  schools:['presocratic'], era:'ancient', blurb:'心灵（Nous）安排万物。', blurb_en:'Nous orders all things.' },
  { id:'empedocles',  zh:'恩培多克勒',   en:'Empedocles',    year:-494, died:-434,  schools:['presocratic'], era:'ancient', blurb:'四元素说；爱与争。', blurb_en:'Four elements; love and strife.' },
  { id:'cicero',      zh:'西塞罗',       en:'Cicero',        year:-106, died:-43,   schools:['stoic','skeptic'], era:'ancient', blurb:'罗马折衷主义；拉丁化希腊哲学。', blurb_en:'Latinized Greek philosophy.' },
  { id:'lucretius',   zh:'卢克莱修',     en:'Lucretius',     year:-99,  died:-55,   schools:['epicurean'], era:'ancient', blurb:'《物性论》；伊壁鸠鲁主义诗篇。', blurb_en:'On the Nature of Things.' },
  { id:'seneca',      zh:'塞涅卡',       en:'Seneca',        year:-4,   died:65,    schools:['stoic'], era:'ancient', blurb:'罗马斯多葛；论生命之短促。', blurb_en:'Roman Stoic; On the Shortness of Life.' },
  { id:'hypatia',     zh:'希帕提娅',     en:'Hypatia',       year:355,  died:415,   schools:['neoplatonic'], era:'ancient', blurb:'亚历山大学派的女哲学家与数学家。', blurb_en:'Alexandrian philosopher and mathematician.' },

  // Medieval
  { id:'maimonides',  zh:'迈蒙尼德',     en:'Maimonides',    year:1138, died:1204,  schools:['scholastic'], era:'medieval', blurb:'犹太亚里士多德主义；《迷途指津》。', blurb_en:'Jewish Aristotelianism; Guide for the Perplexed.' },
  { id:'scotus',      zh:'邓·司各脱',   en:'Duns Scotus',   year:1266, died:1308,  schools:['scholastic'], era:'medieval', blurb:'此性（haecceitas）；意志的优先性。', blurb_en:'Haecceity; primacy of the will.' },

  // Early modern feminist & spiritual
  { id:'wollstonecraft',zh:'沃斯通克拉夫特',en:'Wollstonecraft',year:1759,died:1797, schools:['enlightenment'], era:'early_modern', blurb:'《女权辩护》；早期女性主义。', blurb_en:'Vindication of the Rights of Woman.' },

  // 20th-century mystical / political
  { id:'weil',        zh:'西蒙娜·薇依', en:'Simone Weil',   year:1909, died:1943,  schools:['existentialism','phenomenology'], era:'modern', blurb:'神秘主义、注意力与劳动。', blurb_en:'Mysticism, attention, and labor.' },
];

// Wikipedia article titles for portrait fetching. Override only when the `en`
// field doesn't match a Wikipedia page directly.
const WIKI_TITLES = {
  thales:       'Thales_of_Miletus',
  zeno_elea:    'Zeno_of_Elea',
  zeno_citium:  'Zeno_of_Citium',
  marcus:       'Marcus_Aurelius',
  bacon:        'Francis_Bacon',
  pascal:       'Blaise_Pascal',
  mill:         'John_Stuart_Mill',
  james:        'William_James',
  moore:        'G._E._Moore',
  whitehead:    'Alfred_North_Whitehead',
  husserl:      'Edmund_Husserl',
  bergson:      'Henri_Bergson',
  russell:      'Bertrand_Russell',
  wittgenstein: 'Ludwig_Wittgenstein',
  heidegger:    'Martin_Heidegger',
  arendt:       'Hannah_Arendt',
  sartre:       'Jean-Paul_Sartre',
  beauvoir:     'Simone_de_Beauvoir',
  merleau:      'Maurice_Merleau-Ponty',
  camus:        'Albert_Camus',
  quine:        'Willard_Van_Orman_Quine',
  austin:       'J._L._Austin',
  adorno:       'Theodor_W._Adorno',
  levi_strauss: 'Claude_L%C3%A9vi-Strauss',
  rawls:        'John_Rawls',
  foucault:     'Michel_Foucault',
  habermas:     'J%C3%BCrgen_Habermas',
  derrida:      'Jacques_Derrida',
  rorty:        'Richard_Rorty',
  deleuze:      'Gilles_Deleuze',
  kripke:       'Saul_Kripke',
  davidson:     'Donald_Davidson_(philosopher)',
  butler:       'Judith_Butler',
  zizek:        'Slavoj_%C5%BDi%C5%BEek',
  benjamin:     'Walter_Benjamin',
  lewis_d:      'David_Lewis_(philosopher)',
  searle:       'John_Searle',
  dennett:      'Daniel_Dennett',
  chalmers:     'David_Chalmers',
  parfit:       'Derek_Parfit',
  singer:       'Peter_Singer',
  putnam:       'Hilary_Putnam',
  sellars:      'Wilfrid_Sellars',
  carnap:       'Rudolf_Carnap',
  schlick:      'Moritz_Schlick',
  tarski:       'Alfred_Tarski',
  popper:       'Karl_Popper',
  kuhn:         'Thomas_Kuhn',
  gadamer:      'Hans-Georg_Gadamer',
  levinas:      'Emmanuel_Levinas',
  chomsky:      'Noam_Chomsky',
  nozick:       'Robert_Nozick',
  macintyre:    'Alasdair_MacIntyre',
  barthes:      'Roland_Barthes',
  althusser:    'Louis_Althusser',
  lacan:        'Jacques_Lacan',
  ricoeur:      'Paul_Ric%C5%93ur',
  buber:        'Martin_Buber',
  jaspers:      'Karl_Jaspers',
  marcuse:      'Herbert_Marcuse',
  horkheimer:   'Max_Horkheimer',
  gramsci:      'Antonio_Gramsci',
  fichte:       'Johann_Gottlieb_Fichte',
  schelling:    'Friedrich_Wilhelm_Joseph_Schelling',
  schopenhauer: 'Arthur_Schopenhauer',
  feuerbach:    'Ludwig_Feuerbach',
  kierkegaard:  'S%C3%B8ren_Kierkegaard',
  marx:         'Karl_Marx',
  peirce:       'Charles_Sanders_Peirce',
  nietzsche:    'Friedrich_Nietzsche',
  frege:        'Gottlob_Frege',
  saussure:     'Ferdinand_de_Saussure',
  dewey:        'John_Dewey',
  bentham:      'Jeremy_Bentham',
  voltaire:     'Voltaire',
  rousseau:     'Jean-Jacques_Rousseau',
  kant:         'Immanuel_Kant',
  descartes:    'Ren%C3%A9_Descartes',
  spinoza:      'Baruch_Spinoza',
  locke:        'John_Locke',
  leibniz:      'Gottfried_Wilhelm_Leibniz',
  berkeley:     'George_Berkeley',
  hume:         'David_Hume',
  hobbes:       'Thomas_Hobbes',
  // Pre-Socratics, classics
  anaxagoras:   'Anaxagoras',
  empedocles:   'Empedocles',
  lucretius:    'Lucretius',
  cicero:       'Cicero',
  seneca:       'Seneca_the_Younger',
  hypatia:      'Hypatia',
  maimonides:   'Maimonides',
  scotus:       'Duns_Scotus',
  wollstonecraft:'Mary_Wollstonecraft',
  weil:         'Simone_Weil',
};

window.PHI_DATA = { ERAS, SCHOOLS, RELATIONS, PHILOSOPHERS, WIKI_TITLES };
